# Generated by Django 3.0.4 on 2020-06-12 19:15

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200505_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=registration.models.custom_upload_to),
        ),
    ]
