# Generated by Django 2.2.5 on 2019-09-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externo', '0002_auto_20190829_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoexterno',
            name='Adjuntar_Archivo',
            field=models.FileField(blank=True, upload_to='mantenimiento', verbose_name='Adjuntar Archivo'),
        ),
    ]
