# Generated by Django 2.2.5 on 2019-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externo', '0003_auto_20190920_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoexterno',
            name='Fecha_Equipo_Operativo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Fecha de Equipo Operativo'),
        ),
    ]
