# Generated by Django 3.0.4 on 2020-06-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.FileField(blank=True, upload_to='page', verbose_name='Imagen'),
        ),
    ]
