# Generated by Django 2.2.6 on 2019-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='x',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
