# Generated by Django 2.2.6 on 2019-11-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191101_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='x',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
